name: ci

on:
  push:
    branches: [main]
  pull_request: ~
  workflow_dispatch: ~

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - run: pip install ".[dev]"

      - run: pyright

      - run: ruff check .

      - run: black --check .

      - run: isort --check-only .

      - run: mypy .

      - run: pytest -v
